#!/bin/sh

exec rpmbuild \
    --define '_source_payload w9.gzdio' \
    --define '_binary_payload w9.gzdio' \
    --define '_source_filedigest_algorithm  1' \
    --define '_binary_filedigest_algorithm  1' \
    --define "_sourcedir `pwd`" \
    --define "_builddir `pwd`" \
    --define "_srcrpmdir `pwd`" \
    --define "_rpmdir `pwd`" \
    --define 'dist %{nil}' \
    --nodeps \
    -ba \
    "$@"

# vi: set ai et:
